# Configuraciones de "Derafu".
derafu:

    # Configuraciones para la biblioteca de "Derafu".
    lib:

        # Configuraciones generales asociadas a los servicios.
        services:

            # Prefijo con el que deben ser nombrados todos los servicios
            # asociados a la aplicación. Esto se utiliza especialmente al
            # nombrar paquetes.
            prefix: libredte.lib.

            # Clase para el registro de los servicios de la aplicación.
            serviceRegistryClass: libredte\lib\Core\ServiceRegistry

    # Configuraciones para paquetes.
    packages:
        prime:
            components:
                entity:
                    workers:
                        datasource_provider:
                            normalization:
                                idAttribute: codigo
                                nameAttribute: glosa
                log:
                    workers:
                        logger:
                            channel: libredte_lib
